before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - cp .sample.env .env
  - psql -c 'create database "radfords_test";' -U postgres
  - bundle exec rake db:migrate db:test:prepare
branches:
  only:
    - master
cache:
  - bundler
language:
  - ruby
notifications:
  email:
    - false
  slack:
    secure: GQ3iBioeING+mB1H2NiWURymJmeXk+1Y6A0k2ZcCBsAYnBx15OPuu6svXtSHMo0cHX2dN9PbaVUtD0WiAf/JXGZ1rsiaNecsio/ZBWWQ+KEIlEPe485stHv5JoUfGyBvsUWGYBnCqEhW0KFahL8Ny3WUIIkqrg+X8HKozYrpITU=
rvm:
  - 2.1.5
addons:
  postgresql: "9.3"
