language: ruby
rvm:
  - 2.0.0
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate
  - RAILS_ENV=test bundle exec rspec spec
  - RAILS_ENV=test bundle exec cucumber
before_script:
  - psql -c 'create database radfords_test;' -U postgres
env:
  global:
    - AWS_ACCESS_KEY_ID=foo
    - AWS_SECRET_ACCESS_KEY=bar
    - S3_BUCKET_NAME=local-radfords-assets
    - S3_HOST_NAME=s3-eu-west-1.amazonaws.com
    - SECRET_TOKEN=0db949998a0739081af648218bd39a67
