development:
  adapter: postgresql
  encoding: utf8
  database: radfords_development
  pool: 5
  username:
  password:

test: &test
  adapter: postgresql
  encoding: utf8
  database: radfords_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: radfords_production
  pool: 5
  username:
  password:

postgres:
  adapter: postgresql
  database: radfords_test
  username:
cucumber:
  <<: *test